language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

sudo: false

install:
  - pip install nose-cov python-coveralls
  - pip install -r requirements.txt

# Run test
script:
  - nosetests --with-cov --cov pyexec -v -s

# Calculate coverage
after_success:
  - coveralls
  - openssl aes-256-cbc -K $encrypted_0520e4c07e24_key -iv $encrypted_0520e4c07e24_iv -in .pypirc.enc -out ~/.pypirc -d
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" ]; then
      make publish;
    fi

notifications:
  slack: 3point:n4uGopqXrpbYFbslpV5z0tyO
  email: false
